### ISSUE TITLE
How does Hatchway differ from Django Ninja and DRF?

### ISSUE THREAD

**Issue by quique** [andrewgodwin/django-hatchway#2]
I think it would be worthwhile having a document comparing Hatchway to [Ninja](https://django-ninja.rest-framework.com/), as both are inspired by FastAPI and seem to have the same goals.

As a developer, I would like to know what are the strong and weak points of each one.

**Comment by andrewgodwin** [comment]
We'll get there eventually - I need to get a proper docs folder set up first rather than just a README!

**Comment by fabiocaccamo** [comment]
Even a quick and dirty comparison in the `README` would be better than nothing.

**Comment by quique** [comment]
Richard is certainly right.
Feature comparison and stating the current status of the project can be done (or at least started) by anyone with some knowledge and time.

There is however something that probably can only be written by Andrew himself, and that's the rationale of this project.
I mean some sort of motivation that answers «Django Hatchway looks basically the same as Django Ninja, so why not just use Ninja?».
Some kind of roadmap, however sketchy, would also be nice.

I believe such a document could be useful to attract other developers that would perhaps even get involved with the project.

**Comment by andrewgodwin** [comment]
I published the code as open-source early in its development cycle so others could see it and take a look; it is not ready for full production use elsewhere yet, and as such nobody should be expecting it to be fully documented.

I'm going to close this issue as the discussion is not useful; a document like this will come, in time, but it may be a while, depending on my schedule and how much time is left for open-source work.

**Comment by quique** [comment]
Ok, we should manage our expectations  😇

By the way:  thank you for your work, Andrew!!  You rock!  💪
