### ISSUE TITLE
Add Documentation to Django Hatchway API Framework

### ISSUE THREAD

**Issue by godd0t** [andrewgodwin/django-hatchway#3]
### Description:

Hello @andrewgodwin,

I am a user of your Django Hatchway API Framework, and I am experimenting with it for one of my projects. I really like the project and think it has a lot of potential, but I have noticed that the documentation is missing.

### Proposed Solution:

My proposed solution is to use mkdocs-material (https://squidfunk.github.io/mkdocs-material/) to create comprehensive documentation for the Django Hatchway API Framework.

I am willing to help develop an initial version of the documentation, which can serve as a starting point for further improvements. This will involve creating an outline of the different components of the framework and documenting how to use each one. I will also ensure that the documentation is easy to understand and accessible to users of all skill levels.

### Additional Information:

I believe that improving the documentation for the Django Hatchway API Framework will be a valuable contribution to the project, and I look forward to hearing your thoughts on this proposal.

Thank you for your time and consideration.

**Comment by andrewgodwin** [comment]
I would want to use Sphinx for documentation, as that's what I'm used to from my other projects, and it's easy to get it published - in addition, I mostly want to focus on quickstart docs and explanations first rather than precise reference docs.

**Comment by godd0t** [comment]
Thanks for getting back to me. I appreciate your preference for Sphinx, and I completely understand your desire to focus on quickstart docs and explanations first.
I actually have an initial version of the documentation ready to go, and it uses GitHub Pages for deployment. The deployment process is straightforward, and I can have it online within minutes for you to check it out.
Before doing so, however, I want to make sure I have your permission to proceed with the deployment. If you're open to it, I believe that having this initial version online will make it easier to discuss any improvements or changes that need to be made.

**Comment by andrewgodwin** [comment]
Sorry, but I want to do the documentation myself, as I have a very specific way of writing and structuring it that would make doing it from an existing attempt more difficult. Thanks for the offer, though.
