### ISSUE TITLE
Upgrading to Pydantic V2

### ISSUE THREAD

**Issue by vu3jej** [andrewgodwin/django-hatchway#5]
Are there any plans for upgrading Pydantic V2?

**Comment by andrewgodwin** [comment]
Not right now - I want to reconsider this library's design a bit before I make any more changes!

**Comment by Cellesti** [comment]
Hello, i maintain Alpine Linux's django-hatchway package, and pydantic in Alpine was upgraded to V2 last week (as part of a larger Python 3.12-Pytest 8-Cython 3 upgrade).

With the upgrade to pydantic 2, i noticed that django-hatchway's `tests/test_view.py::test_string_not_list` is now failing.

May i know if it is just the test that needs updating, or is the whole module incompatible with pydantic 2?

If it's the latter, could it be solved for now by changing `from pydantic import` to `from pydantic.v1 import`? (I can do this with a patch to the Alpine package.)

Thank you.

**Comment by andrewgodwin** [comment]
The whole module is currently on pydantic v1, and I don't plan on changing this soon as I'm currently not actively doing development, so if you need to patch to make it work on Alpine I'd suggest you do that.
